# Homework for Week 6

The goal for this homework is to see the relevant journalistic uses for what we learned in class.

1. Ingest different types of spreadsheets into Pandas,
2. Gather general info about our dataframes
3. Target specific values

## Pandas - Importing data

Please download the following data and move it to an appropriate folder on your computer:

- <a href="https://github.com/sandeepmj/datasets/blob/main/importing-excerpts/ems20_1st_6months_excerpt.csv">EMS excerpt</a>,

- <a href="https://github.com/sandeepmj/datasets/blob/main/importing-excerpts/multi-data.xlsx">Customs, Border Patrol</a>

**Give yourself time to download it. Some of the files are large!**

In [3]:
## import the pandas library in this cell

import pandas as pd

### Ingest the following dataset into this note:

- ```ems20_1st_6months_excerpt.csv``` into a dataframe named ```ems2020_excerpt_df```

In [5]:
## import data and store in dataframe
df = pd.read_csv("data-rawhomework/ems20_1st_6months_excerpt.csv")

In [6]:
## call the first 10 rows
df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
7,201471743,2020-05-26 12:45:46,INJURY,5,INJURY,5,05/26/2020 12:46:04 PM,Y,18,05/26/2020 12:46:15 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk171.csv
8,201180116,2020-04-27 00:57:48,EDP,7,EDPC,7,04/27/2020 12:58:07 AM,Y,19,04/27/2020 12:58:15 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk170.csv
9,200572739,2020-02-26 15:15:25,CARDBR,2,CARDBR,2,02/26/2020 03:16:35 PM,Y,70,02/26/2020 03:16:49 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk167.csv

In [7]:
## call the last 5 rows
df.tail()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [8]:
## call a 20 random rows
df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
3568,200090495,2020-01-09 04:54:44,MCI21,2,MCI21,2,01/09/2020 04:54:55 AM,Y,11,01/09/2020 04:55:13 AM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
5544,201015292,2020-04-10 23:39:31,SICKFC,6,SICKFC,6,04/11/2020 12:55:40 AM,Y,4569,04/11/2020 12:55:59 AM,...,46.0,15.0,205.0,9.0,15.0,Y,N,N,N,chunk169.csv
9881,200431432,2020-02-12 10:40:36,MVAINJ,4,MVAINJ,4,02/12/2020 10:42:11 AM,Y,95,02/12/2020 10:42:28 AM,...,113.0,28.0,412.0,27.0,5.0,N,N,N,N,chunk166.csv
4320,200393960,2020-02-08 22:07:38,RESPIR,4,RESPIR,4,02/08/2020 10:08:08 PM,Y,30,02/08/2020 10:08:31 PM,...,70.0,45.0,314.0,22.0,9.0,N,N,N,N,chunk166.csv
8067,200651712,2020-03-05 11:38:33,DIFFBR,2,DIFFBR,2,03/05/2020 11:38:56 AM,Y,23,03/05/2020 11:39:11 AM,...,100.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk167.csv
6755,201051104,2020-04-14 08:28:38,ARREST,1,ARREST,1,04/14/2020 08:28:46 AM,Y,8,04/14/2020 08:29:11 AM,...,47.0,12.0,212.0,11.0,16.0,N,N,N,N,chunk169.csv
4484,200803326,2020-03-20 16:03:41,SICK,6,SICK,6,03/20/2020 05:06:42 PM,Y,3781,03/20/2020 05:08:28 PM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk168.csv
3886,200750863,2020-03-15 05:00:41,RESPIR,4,RESPIR,4,03/15/2020 05:00:52 AM,Y,11,03/15/2020 05:01:08 AM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk168.csv
575,200422997,2020-02-11 15:59:02,INJMAJ,3,INJMAJ,3,02/11/2020 03:59:14 PM,Y,12,02/11/2020 03:59:32 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk166.csv
4512,201073431,2020-04-16 19:31:33,DIFFFC,2,SICK,6,04/16/2020 07:32:59 PM,Y,86,04/16/2020 07:33:13 PM,...,108.0,26.0,402.0,30.0,14.0,N,N,N,N,chunk169.csv
4222,200191883,2020-01-19 12:19:44,ALTMEN,3,ALTMEN,3,01/19/2020 12:20:07 PM,Y,23,01/19/2020 12:20:31 PM,...,60.0,47.0,313.0,21.0,11.0,N,N,N,N,chunk165.csv
6857,201731499,2020-06-21 10:59:18,STATEP,2,STATEP,2,06/21/2020 10:59:26 AM,Y,8,06/21/2020 10:59:36 AM,...,61.0,48.0,315.0,22.0,9.0,N,N,N,N,chunk172.csv
10999,201652559,2020-06-13 17:21:58,CVA,4,CVA,4,06/13/2020 05:22:08 PM,Y,10,06/13/2020 05:22:40 PM,...,70.0,40.0,314.0,22.0,9.0,N,N,N,N,chunk171.csv
6497,200642860,2020-03-04 16:01:26,UNC,2,UNC,2,03/04/2020 04:01:31 PM,Y,5,03/04/2020 04:01:54 PM,...,66.0,44.0,312.0,20.0,10.0,N,N,N,N,chunk167.csv
2408,201211318,2020-04-30 11:40:07,ALTMFC,3,ALTMFC,3,04/30/2020 11:40:11 AM,Y,4,04/30/2020 11:40:23 AM,...,113.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk170.csv
8315,200222983,2020-01-22 16:21:12,SICK,6,SICK,6,01/22/2020 04:21:19 PM,Y,7,01/22/2020 04:22:19 PM,...,84.0,33.0,302.0,13.0,7.0,N,N,N,N,chunk166.csv
2504,200042611,2020-01-04 15:27:31,UNKNOW,4,UNKNOW,4,01/04/2020 03:28:05 PM,Y,34,01/04/2020 03:28:24 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk165.csv
4418,201632640,2020-06-11 17:06:43,UNKNOW,4,UNKNOW,4,06/11/2020 05:06:54 PM,Y,11,06/11/2020 05:07:07 PM,...,70.0,44.0,314.0,22.0,9.0,N,N,N,N,chunk171.csv
8836,200122661,2020-01-12 15:33:12,SICK,6,SICK,6,01/12/2020 03:33:23 PM,Y,11,01/12/2020 03:33:43 PM,...,120.0,49.0,501.0,31.0,11.0,N,N,N,N,chunk165.csv
11776,200411149,2020-02-10 08:51:28,UNKNOW,4,UNKNOW,4,02/10/2020 08:51:36 AM,Y,8,02/10/2020 08:51:47 AM,...,109.0,19.0,407.0,25.0,14.0,N,N,N,N,chunk166.csv

In [9]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

In [10]:
## basic overview of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13117 entries, 0 to 13116
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CAD_INCIDENT_ID                 13117 non-null  int64
 1   INCIDENT_DATETIME               13117 non-null  object
 2   INITIAL_CALL_TYPE               13117 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     13117 non-null  int64
 4   FINAL_CALL_TYPE                 13117 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       13117 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       13010 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  13117 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    13117 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       12988 non-null  object
 10  FIRST_ON_SCENE_DATETIME         12533 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  13117 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    12533 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   12533 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          7870 non-null   object
 15  FIRST_HOSP_ARRIVAL_DATETIME     7791 non-null   object
 16  INCIDENT_CLOSE_DATETIME         13110 non-null  object
 17  HELD_INDICATOR                  13117 non-null  object
 18  INCIDENT_DISPOSITION_CODE       12985 non-null  float64
 19  BOROUGH                         13117 non-null  object
 20  INCIDENT_DISPATCH_AREA          13117 non-null  object
 21  ZIPCODE                         12987 non-null  float64
 22  POLICEPRECINCT                  12988 non-null  float64
 23  CITYCOUNCILDISTRICT             12988 non-null  float64
 24  COMMUNITYDISTRICT               12988 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         12978 non-null  float64
 26  CONGRESSIONALDISTRICT           12988 non-null  float64
 27  REOPEN_INDICATOR                13117 non-null  object
 28  SPECIAL_EVENT_INDICATOR         13117 non-null  object
 29  STANDBY_INDICATOR               13117 non-null  object
 30  TRANSFER_INDICATOR              13117 non-null  object
 31  source                          13117 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 3.2+ MB

In [11]:
## call the top 7 rows
df.head(7)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv

In [12]:
## call a sample of 10
df.sample(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
12191,200362135,2020-02-05 13:07:14,SICK,6,SICK,6,02/05/2020 01:07:38 PM,Y,24,02/05/2020 01:08:31 PM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk166.csv
2554,201382834,2020-05-17 19:19:05,OBMAJ,3,OBMAJ,3,05/17/2020 07:19:14 PM,Y,9,05/17/2020 07:19:19 PM,...,48.0,17.0,206.0,12.0,15.0,N,N,N,N,chunk171.csv
1393,201573612,2020-06-05 20:49:48,ASTHMB,2,ASTHMB,2,06/05/2020 08:50:10 PM,Y,22,06/05/2020 08:50:19 PM,...,100.0,32.0,414.0,27.0,5.0,N,N,N,N,chunk171.csv
3352,201034508,2020-04-12 22:32:45,INJURY,5,INJURY,5,04/12/2020 10:32:57 PM,Y,12,04/12/2020 10:33:14 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk169.csv
10982,201241988,2020-05-03 14:49:46,EDP,7,EDP,7,05/03/2020 02:50:08 PM,Y,22,05/03/2020 02:50:47 PM,...,71.0,35.0,309.0,17.0,9.0,N,N,N,N,chunk170.csv
10545,201701233,2020-06-18 10:59:15,UNC,2,UNC,2,06/18/2020 10:59:32 AM,Y,17,06/18/2020 10:59:51 AM,...,49.0,12.0,211.0,11.0,16.0,N,N,N,N,chunk172.csv
12055,200463507,2020-02-15 20:20:42,ARREST,1,ARREST,1,02/15/2020 08:21:08 PM,Y,26,02/15/2020 08:22:26 PM,...,81.0,36.0,303.0,16.0,8.0,N,N,N,N,chunk167.csv
6274,200182128,2020-01-18 13:44:30,SICK,6,SICK,6,01/18/2020 01:45:13 PM,Y,43,01/18/2020 01:45:37 PM,...,90.0,34.0,301.0,14.0,7.0,N,N,N,N,chunk165.csv
6117,200511149,2020-02-20 09:41:30,CARD,3,CARD,3,02/20/2020 09:41:43 AM,Y,13,02/20/2020 09:41:49 AM,...,46.0,15.0,205.0,10.0,15.0,N,N,N,N,chunk167.csv
4144,200500476,2020-02-19 03:55:29,EDP,7,EDPC,7,02/19/2020 03:55:40 AM,Y,11,02/19/2020 03:55:42 AM,...,90.0,34.0,301.0,14.0,7.0,N,N,N,N,chunk167.csv

In [13]:
## call the bottom 6
df.tail(6)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13111,200870168,2020-03-27 00:42:59,INJURY,5,INJURY,5,03/27/2020 12:43:13 AM,Y,14,03/27/2020 12:43:28 AM,...,109.0,19.0,407.0,25.0,3.0,N,N,N,N,chunk168.csv
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [59]:
## Programmatically capture the 2245th FINAL_CALL_TYPE value and store in a variable.
call = cbp_df.iloc[2245]["FINAL_CALL_TYPE"]

KeyError: 'FINAL_CALL_TYPE'

## Targeting an Excel sheet

Use the Customs and Border Protection data in this ```multi-data.xlsx``` workbook to answer the following questions.

Create a dataframe called ```cbp_df```.

In [20]:
## import data here
cbp_df = pd.read_excel("data-rawhomework/CBP.xlsx")

In [22]:
## call the top 15 rows

cbp_df.head(15)

,Serial Number,County,License Type Code,License Class Code,Certificate Number,Premise Name,DBA,Premise Address,Premise Address 2,Premise City,...,Premise Zip,License Issued Date,License Expiration Date,Method of Operation,Days/Hours of Operation,Other,Georeference,Zone,Effective Date,Original Date
0,2000777,ALBANY,HL,242,912771,SUPER HOST HOTELS INC,ALBANY RAMADA PLAZA,3 WATERVLIET AVE,NaN,ALBANY,...,12206,2019-11-15,2021-11-30,HOTEL RESTAURANT SERVING BEER WINE CIDER AND L...,NaN,NaN,POINT (-73.783705 42.674761),2,2019-12-01,1996-12-05
1,1197749,NASSAU,CT,246,913036,MEMORARE CATERERS INC,NaN,2183 JACKSON AVE A,WAVERLY AVE & MERRICK ROAD,SEAFORD,...,11783,2019-11-22,2021-11-30,CATERER SERVING BEER CIDER WINE AND LIQUOR,NaN,NaN,POINT (-73.487062 40.668214),1,2019-12-01,2007-12-18
2,2149537,SULLIVAN,AX,122,910149,AHMED TRADING INC,NaN,1302 STATE ROUTE 52,NaN,LOCH SHELDRAKE,...,12759,2018-11-19,2021-11-30,GROCERY SELLING BEER CIDER AND WINE PRODUCTS,NaN,NaN,POINT (-74.66699 41.777859),2,2018-12-01,2009-12-22
3,1311950,QUEENS,W,322,903719,CAOTICO LLC,FORET WINES,68-38 FOREST AVE,STOREFRONT C,RIDGEWOOD,...,11385,2018-12-31,2021-11-30,WINE STORE SELLING WINE,NaN,NaN,POINT (-73.90109 40.702673),1,2018-12-31,2018-12-31
4,2217319,PUTNAM,TW,344,917985,COFFEE TIME CAFE INC,NaN,559 RTE 6N,NaN,MAHOPAC,...,10541,2019-12-05,2021-11-30,TAVERN SERVING BEER AND WINE,NaN,NaN,POINT (-73.763883 41.374319),2,2019-12-05,2019-12-05
5,1319511,NEW YORK,RW,341,831035,DONATELLA MOXY 7TH AVENUE LLC,PROVA PIZZA BAR,485 7TH AVE,GROUND FLOOR,NEW YORK,...,10123,2019-12-23,2021-11-30,"RESTAURANT SERVING WINE, BEER AND CIDER",NaN,Recorded Music Permitted and No Dancing,NaN,1,2019-12-23,2019-12-23
6,2220767,MONTGOMERY,C,103,935317,CUDA BEVERAGE LLC,BILL'S BEVERAGE,1 WILLOW ST,NaN,AMSTERDAM,...,12010,2020-12-14,2021-11-30,WHOLESALE BEER,NaN,NaN,POINT (-74.1866 42.940987),2,2020-12-14,2020-12-14
7,2129283,ALBANY,WS,308,911084,"SILVERADO VINEYARDS, THE",NaN,6121 SILVERADO TRAIL,NaN,NAPA,...,94558,2018-12-03,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,POINT (-122.33304899999999 38.40974),2,2019-01-01,2005-10-19
8,2138381,ALBANY,WS,308,911310,VOLCANO VINEYARDS LLC,VOLCANO WINERY,35 PILMAUNA DRIVE,NaN,VOLCANO,...,96785,2018-12-10,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,NaN,2,2019-01-01,2007-06-28
9,2160505,ALBANY,WS,308,911278,J J COHN ESTATE LLC,NaN,5055 SOLANO AVE,7079689367,NAPA,...,94558,2018-12-10,2021-12-31,OUT OF STATE DIRECT WINE SHIPPER,NaN,NaN,POINT (-122.33301599999999 38.3548),2,2019-01-01,2010-07-02
10,2175892,ALBANY,WS,308,911215,KENEFICK RANCHES WINERY LLC,KENEFICK RANCH WINERY,4550 SILVERADO TRAIL,NaN,CALISTOGA,...,945159647,2018-12-07,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,POINT (-122.54937700000002 38.57468),2,2019-01-01,2011-08-11
11,2188886,ALBANY,WS,308,909969,KSSM LLC,MICHAEL SCHLUMBERGER,4155 WINE CREEK RD,NaN,HEALDSBURG,...,95448,2018-11-08,2021-12-31,NaN,NaN,NaN,POINT (-122.95010999999998 38.656503),2,2019-01-01,2013-01-10
12,2192454,ALBANY,WS,308,918967,TERRAVANT WINE COMPANY LLC,TERRAVANT WINE COMPANY,35 & 70 INDUSTRIAL WAY,NaN,BUELLTON,...,93427,2019-06-17,2021-12-31,NaN,NaN,NaN,POINT (-120.202402 34.609092),2,2019-06-17,2013-08-30
13,1286881,NEW YORK,OP,252,913420,MERMAID 88 LLC,THE MERMAID INN,570-572 AMSTERDAM AVE,NaN,NEW YORK,...,10024,2019-12-05,2021-12-31,"RESTAURANT SERVING BEER, WINE, CIDER AND LIQUOR",RECORDED MUSIC. NO DANCING.,LICENSED SIDEWALK CAFE.,POINT (-73.97424 40.788753),1,2020-01-01,2015-09-15
14,1289791,BRONX,AX,122,912566,NEW FORDHAM FOOD PLAZA INC,NaN,2487 CRESTON AVE,NaN,BRONX,...,10468,2019-01-10,2021-12-31,GROCERY STORE SELLING BEER CIDER AND WINE PROD...,NaN,NaN,POINT (-73.898153 40.862681),1,2019-01-10,2016-01-28

In [25]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
cbp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50140 entries, 0 to 50139
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Serial Number            50140 non-null  int64
 1   County                   50140 non-null  object
 2   License Type Code        50140 non-null  object
 3   License Class Code       50140 non-null  object
 4   Certificate Number       50140 non-null  int64
 5   Premise Name             50139 non-null  object
 6   DBA                      35162 non-null  object
 7   Premise Address          50140 non-null  object
 8   Premise Address 2        10333 non-null  object
 9   Premise City             50140 non-null  object
 10  Premise State            50140 non-null  object
 11  Premise Zip              50140 non-null  object
 12  License Issued Date      50104 non-null  datetime64[ns]
 13  License Expiration Date  50140 non-null  datetime64[ns]
 14  Method of Operation      49730 non-null  object
 15  Days/Hours of Operation  5996 non-null   object
 16  Other                    16432 non-null  object
 17  Georeference             46674 non-null  object
 18  Zone                     50140 non-null  int64
 19  Effective Date           50140 non-null  datetime64[ns]
 20  Original Date            46496 non-null  datetime64[ns]
dtypes: datetime64[ns](4), int64(3), object(14)
memory usage: 8.0+ MB

In [27]:
## call the bottom 3
cbp_df.tail(3)

,Serial Number,County,License Type Code,License Class Code,Certificate Number,Premise Name,DBA,Premise Address,Premise Address 2,Premise City,...,Premise Zip,License Issued Date,License Expiration Date,Method of Operation,Days/Hours of Operation,Other,Georeference,Zone,Effective Date,Original Date
50137,2209433,ONONDAGA,AX,128,784064,7 ELEVEN INC,SUNOCO A PLUS #40215H,1000 W GENESEE ST,NaN,SYRACUSE,...,13204,2021-10-28,2024-10-31,GROCERY STORE SELLING BEER CIDER & WINE PRODUCTS,NaN,NaN,POINT (-76.17092 43.053662),2,2021-11-01,2018-02-01
50138,1312336,BRONX,CM,110,801200,TORCH & CROWN 704 BROADWAY LLC,TORCH & CROWN BREWING COMPANY,463 E 173RD ST,NaN,BRONX,...,10457,2021-11-08,2024-11-30,COMBINED CRAFT MANUFACTURER,Micro Brewer Serial #1312333,Farm Brewer Serial #1312335,POINT (-73.901384 40.841683),1,2021-12-01,2018-12-24
50139,2227379,ALBANY,WS,308,941478,DUSKY GOOSE LLC,DUSKY GOOSE,8355 NE WARREN RD,WWW.DUSKYGOOSE.COM,DUNDEE,...,97115,2021-10-06,2024-09-30,DIRECT WINE SHIPPER,NaN,NaN,POINT (-123.032311 45.276215),2,2021-10-06,2021-10-06

In [29]:
## call a sample of 20
cbp_df.sample(20)

,Serial Number,County,License Type Code,License Class Code,Certificate Number,Premise Name,DBA,Premise Address,Premise Address 2,Premise City,...,Premise Zip,License Issued Date,License Expiration Date,Method of Operation,Days/Hours of Operation,Other,Georeference,Zone,Effective Date,Original Date
25969,2506886,ST LAWRENCE,A,122,920551,SHARLENE & SCOTT LANTRY,HELENA GENERAL STORE,28 MAIN ST,NaN,HELENA,...,13649,2019-08-16,2022-09-30,GROCERY STORE SELLING BEER & CIDER ONLY,NaN,NaN,POINT (-74.893079 44.932522),2,2019-10-01,2004-11-22
37275,2013906,WARREN,AX,128,845093,STEWART'S SHOPS CORP,STEWART'S SHOP #282,977 STATE RTE 149,NaN,QUEENSBURY,...,12804,2021-06-01,2024-07-31,"CONVENIENCE STORE SELLING BEER, CIDER AND WINE...",NaN,NaN,NaN,2,2021-08-01,NaT
16108,2158112,ALBANY,WS,308,911685,BRICK HOUSE WINE COMPANY,NaN,18200 LEWIS ROGERS LANE,NaN,NEWBERG,...,97132,2018-12-19,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,POINT (-123.072439 45.347721),2,2019-01-01,2010-03-23
35213,3156231,TIOGA,OP,252,796085,AINDARA INC,ORIGINAL ITALIAN PIZZA & RESTAURANT OF OWEGO,25 LAKE ST,NaN,OWEGO,...,13827,2021-06-10,2023-06-30,RESTAURANT SERVING BEER CIDER WINE AND LIQUOR,NaN,NaN,POINT (-76.261226 42.103138),3,2021-07-01,2015-07-08
37444,1174595,KINGS,AX,122,937432,DEKALB CONVENIENCE INC,DEKALB CONVENIENCE,249 DEKALB AVE,NaN,BROOKLYN,...,11205,2021-03-17,2024-04-30,GROCERY STORE SELLING BEER CIDER AND WINE PRODUCT,NaN,NaN,POINT (-73.969337 40.689475),1,2021-05-01,2006-05-02
15153,3155191,ONTARIO,OP,252,922307,NICKS CHOPHOUSE INC,NaN,3-7 BEEMAN ST AND 195 MAIN ST,NaN,CANANDAIGUA,...,14424,2020-06-16,2022-07-31,"RESTAURANT SERVING LIQUOR, BEER, WINE, & CIDER",Live and Recorded Music,Licensed Sidewalk Cafe & Rooftop,NaN,3,2020-08-01,2014-08-19
4947,2106323,ULSTER,OP,252,924222,ZOFIA MIODUSZEWSKI,RUNNING DEER INN,28 ROUTE 55 WEST,NaN,NAPANOCH,...,12458,2020-07-21,2022-07-31,TAVERN SERVING BEER WINE CIDER AND LIQUOR,NaN,NaN,NaN,2,2020-08-01,2017-04-19
23789,2164092,ONONDAGA,OP,252,928699,TARDIBONE ENTERPRISES LLC,KEGS & EGGS,7 NORTH HAMILTON STREET,NaN,JORDAN,...,13080,2020-11-23,2022-12-31,"RESTAURANT SERVING BEER, WINE, LIQUOR, & CIDER",NaN,"Music & Dancing Permitted, Licensed Yard/Pavil...",POINT (-76.477131 43.067127),2,2021-01-01,2011-01-11
30052,3149367,STEUBEN,A,122,922173,RONALD L ABBEY III,BEARTOWN BEVERAGE,3 BEARTOWN ROAD,NaN,PAINTED POST,...,14870,2019-11-06,2022-11-30,GROCERY STORE SELLING BEER & CIDER,NaN,NaN,POINT (-77.111435 42.146344),3,2019-12-01,2010-12-08
11054,2156594,ALBANY,WS,308,911297,AKA WINES LLC,SCRIBE WINERY,21684 EIGHTH STREET EAST,NaN,SONOMA,...,95476,2018-12-10,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,POINT (-122.440441 38.260169),2,2019-01-01,2010-02-01
41263,2200087,ULSTER,L,222,845436,JPM ENDEAVORS INCORPORATED,MALONEY'S WINES & LIQUOR,3139 RTE 9W,UNIT 8,SAUGERTIES,...,12477,2021-06-08,2024-07-31,LIQUOR STORE,NaN,NaN,POINT (-73.954787 42.057142),2,2021-08-01,2015-08-07
430,1115986,SUFFOLK,AX,123,913048,EAST END MARKETING CORP,WEST HAMPTON BEACH COASTAL,112 MONTAUK HWY,NaN,WEST HAMPTON BEACH,...,11978,2019-02-01,2022-03-31,GROCERY STORE SELLING BEER CIDER AND WINE PROD...,NaN,NaN,POINT (-72.646466 40.821822),1,2019-04-01,NaT
9582,1022414,NEW YORK,C,103,939926,NEW YORK BEVERAGE WHOLESALERS CORP,NaN,515 BRUCKNER BLVD,NaN,BRONX,...,10455,2021-04-21,2022-06-30,WHOLESALE BEER,NaN,NaN,POINT (-73.902157 40.810511),1,2021-07-01,1996-05-30
32273,2210268,ALBANY,WS,308,935585,CEDARVILLE VINEYARD & WINERY LLC,CEDARVILLE VINEYARD,6320 MARESTAIL RD,NaN,FAIR PLAY,...,95684,2020-12-14,2023-11-30,DIRECT WINE SHIPPER,NaN,NaN,POINT (-120.67316399999999 38.597214),2,2020-12-14,2017-12-04
44703,1254579,QUEENS,AX,122,933922,JR FAMILY GROCERY INC,NaN,39 02 104TH ST,NaN,CORONA,...,11368,2020-08-21,2023-08-31,"GROCERY STORE SELLING BEER, CIDER AND WINE PRO...",NaN,NaN,NaN,1,2020-09-01,2011-09-20
39556,2500834,CAYUGA,AX,123,847156,WEGMANS FOOD MARKETS INC,WEGMANS,1 LOOP ROAD,NaN,AUBURN,...,13021,2021-06-30,2024-06-30,GROCERY STORE SELLING BEER CIDER AND WINE PROD...,NaN,NaN,POINT (-76.563976 42.930818),2,2021-07-01,2002-09-05
15952,1288582,NEW YORK,OP,252,914238,MSG ARENA LLC,MADISON SQUARE GARDEN,4 PENNSYLVANIA PLAZA,NaN,NEW YORK,...,10121,2020-01-15,2022-01-31,"ARENA SERVING BEER, CIDER, WINE AND LIQUOR",LEVEL 2 GOLD BAR A,Live music,NaN,1,2020-02-01,2016-02-23
43042,3164892,CHAUTAUQUA,L,222,933224,NAKED GRACE LLC,B K WINE & SPIRITS,107 W MAIN ST,NaN,SHERMAN,...,14781,2020-08-31,2023-07-31,LIQUOR STORE SELLING WINE AND LIQUOR,NaN,NaN,POINT (-79.597339 42.159327),3,2020-08-31,2020-08-31
28197,2207001,ULSTER,OP,252,920250,WHO COOKS FOR YOU LLC,HOOT OWL,26 AWOSTING RD,NaN,PINE BUSH,...,12566,2021-03-31,2023-03-31,RESTAURANT SERVING BEER WINE CIDER & LIQUOR,NaN,Recorded/Live Music; Sidewalk Cafe,POINT (-74.264175 41.648687),2,2021-04-01,2017-04-13
44310,1327036,NASSAU,AX,122,933366,PRAGAT 197 INC,CIGAR SHOP,197 FRANKLIN AVE,NaN,FRANKLIN SQUARE,...,11010,2020-09-17,2023-08-31,"GROCERY STORE SELLING BEER, WINE PRODUCTS & CIDER",NaN,NaN,POINT (-73.678992 40.702704),1,2020-09-17,2020-09-17

In [35]:
## Programmatically capture the 8th hours_in_custody value and store in a variable.

In [51]:
hours = cbp_df.iloc[7]["hours_in_custody"]

KeyError: 'hours_in_custody'